from pydantic import BaseModel, EmailStr, Field, ConfigDict, field_validator
from typing import Optional
from datetime import datetime


class UserCreate(BaseModel):
    email: EmailStr
    password: str
    full_name: str
    role: str = "patient"  # 'patient', 'gp', or 'admin'
    # Patient context fields (optional at registration)
    age: Optional[int] = Field(None, ge=1, le=120)
    pain_level: Optional[int] = Field(None, ge=0, le=10, description="Self-reported pain 0-10")
    mobility_level: Optional[str] = Field(None, description="'limited', 'moderate', or 'good'")
    has_support: Optional[bool] = Field(None, description="Is there someone to help them?")


class UserOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    
    user_id: int
    email: EmailStr
    full_name: str
    role: str
    age: Optional[int] = None
    pain_level: Optional[int] = None
    mobility_level: Optional[str] = None
    has_support: Optional[bool] = None
    created_at: datetime


class Token(BaseModel):
    access_token: str
    token_type: str


class ForgotPasswordRequest(BaseModel):
    email: EmailStr


class ResetPasswordRequest(BaseModel):
    """
    Schema for password reset requests from mobile app.
    
    Expected JSON body:
    {
        "token": "jwt_token_string",
        "new_password": "new_secure_password"
    }
    
    The token should be a valid password reset token generated by the backend.
    The new_password must be at least 8 characters long.
    """
    token: str = Field(
        ..., 
        description="Password reset JWT token from email link",
        min_length=10  # JWT tokens are typically much longer
    )
    new_password: str = Field(
        ...,
        description="New password (minimum 8 characters)",
        min_length=8,
        max_length=128
    )
    
    @field_validator('new_password')
    @classmethod
    def validate_password_strength(cls, v):
        """Validate password meets strength requirements."""
        if not v or len(v) < 8:
            raise ValueError('Password must be at least 8 characters long')
        
        # Additional strength checks
        has_uppercase = any(c.isupper() for c in v)
        has_lowercase = any(c.islower() for c in v)
        has_digit = any(c.isdigit() for c in v)
        has_special = any(c in '!@#$%^&*()_+-=[]{}|;:,.<>?' for c in v)
        
        if not (has_uppercase and has_lowercase and has_digit):
            raise ValueError(
                'Password must contain at least one uppercase letter, '
                'one lowercase letter, and one number'
            )
        
        return v
    
    @field_validator('token')
    @classmethod
    def validate_token_format(cls, v):
        """Basic validation that token looks like a JWT."""
        if not v or not isinstance(v, str):
            raise ValueError('Token must be a non-empty string')
        
        # JWT tokens have 3 parts separated by dots
        parts = v.split('.')
        if len(parts) != 3:
            raise ValueError('Token must be a valid JWT format (3 parts separated by dots)')
        
        return v