"""add_patient_context_columns_to_user

Revision ID: d932d8cf9437
Revises: add_profile_log
Create Date: 2026-03-30 13:16:23.843048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd932d8cf9437'
down_revision: Union[str, None] = 'add_profile_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('USER', sa.Column('pain_level', sa.Integer(), nullable=True))
    op.add_column('USER', sa.Column('mobility_level', sa.String(), nullable=True))
    op.add_column('USER', sa.Column('has_support', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'has_support')
    op.drop_column('USER', 'mobility_level')
    op.drop_column('USER', 'pain_level')
    op.drop_column('USER', 'age')
    # ### end Alembic commands ###
