"""create initial tables

Revision ID: 0c1e48cb9649
Revises: 
Create Date: 2026-03-29 14:47:38.008548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1e48cb9649'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EXERCISE_VIDEO',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('kl_grade_min', sa.Integer(), nullable=False),
    sa.Column('kl_grade_max', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_index(op.f('ix_EXERCISE_VIDEO_video_id'), 'EXERCISE_VIDEO', ['video_id'], unique=False)
    op.create_table('USER',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_USER_email'), 'USER', ['email'], unique=True)
    op.create_index(op.f('ix_USER_user_id'), 'USER', ['user_id'], unique=False)
    op.create_table('IMAGE',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('processed_s3_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_IMAGE_image_id'), 'IMAGE', ['image_id'], unique=False)
    op.create_table('REPORT',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kl_grade', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('lifestyle_plan', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('exercise_video_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['IMAGE.image_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_REPORT_report_id'), 'REPORT', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_REPORT_report_id'), table_name='REPORT')
    op.drop_table('REPORT')
    op.drop_index(op.f('ix_IMAGE_image_id'), table_name='IMAGE')
    op.drop_table('IMAGE')
    op.drop_index(op.f('ix_USER_user_id'), table_name='USER')
    op.drop_index(op.f('ix_USER_email'), table_name='USER')
    op.drop_table('USER')
    op.drop_index(op.f('ix_EXERCISE_VIDEO_video_id'), table_name='EXERCISE_VIDEO')
    op.drop_table('EXERCISE_VIDEO')
    # ### end Alembic commands ###
